name: CI - Test the templates
on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Get changed files ğŸ”
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ros2: ./**/ros2/**
            texlive: ./**/texlive/**

  test:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    env:
      BUILDKIT_INLINE_CACHE: "1"
      BUILDKIT_PROGRESS: "plain"
    continue-on-error: true
    strategy:
      matrix:
        templates: ${{ fromJSON(needs.detect-changes.outputs.templates) }}
    steps:
      - name: Checkout ğŸ¯
        uses: actions/checkout@v3

      - name: Smoke test for '${{ matrix.templates }}' ğŸš§
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          template: "${{ matrix.templates }}"
